settings=
{
	["tad_profiles"]=
	{
	},
	["default_profile"]=
	{
		[0]=
		{
			["range_rings"]=true,
			["spi_display"]=1,
			["tag_info"]=1,
			["frequency_mapping"]=8,
			["bullseye"]=true,
			["ownship_waypoints"]=true,
			["LCN2"]="00",
			["guardChannel1"]=3,
			["LCN1"]="00",
			["ground_key"]="A",
			["name"]="DFLT",
			["guardChannel2"]=7,
			["air_key"]="1",
			["flight_plan_lines"]=true,
			["waypoint_labels"]=true,
			["gateway_key"]="1",
		},
	},
}
